FROM mysql

# Copy the database schema to the /data directory
COPY epcis_schema.sql /data/epcis_schema.sql

# Change the working directory
WORKDIR data

#CMD mysql -h database-1.cwzu0j3wgavr.us-east-1.rds.amazonaws.com -u admin -p admin123 studentapp < epcis_schema.sql

#CMD mysql -h database-2.cwzu0j3wgavr.us-east-1.rds.amazonaws.com -u admin -p


